
services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    restart: always

  ngrok:
    image: ngrok/ngrok:latest
    depends_on:
      - flask-app
    environment:
      NGROK_AUTHTOKEN: your-ngrok-authtoken  # Replace with your ngrok authtoken
    ports:
      - "4040:4040"  # Ngrok web interface
    command: http flask-app:5000  # Forward traffic to the Flask app